---
- name: Initial setup
  hosts: all
  become: true
  roles:
    - init

- name: Web server
  hosts: web_servers
  become: true
  roles:
    - agama
    - uwsgi
    - nginx

- name: Database server
  hosts: db_servers
  roles:
    - mysql
