- name: Gather facts from all hosts
  hosts: all
  gather_facts: yes
  tasks: []

- name: Initial setup
  hosts: all
  become: true
  roles:
    - init
  tags: init

- name: DNS server
  hosts: dns_servers
  become: true
  roles:
    - bind
  tags: bind

- name: DNS resolver
  hosts: all
  become: true
  gather_facts: yes
  roles: 
    - resolve
  tags: bind

- name: Database servers
  hosts: db_servers
  become: true
  roles:
    - mysql
  tags: mysql

- name: MySQL replication
  hosts: db_servers
  become: true
  roles:
    - mysql_replication
  tags: mysql

- name: Web servers
  hosts: web_servers
  become: true
  roles:
    - docker
    - agama
    - nginx
  tags: nginx

- name: Prometheus server
  hosts: prometheus
  roles:
    - nginx
    - prometheus
  tags: prom

- name: Grafana
  hosts: grafana
  roles:
    - docker
    - nginx
    - grafana
  tags: g

- name: Logging server setup
  hosts: loki
  roles:
    - loki
  tags: loki

- name: HAProxy load balancers
  hosts: haproxy
  become: true
  roles:
    - haproxy
    - keepalived
  tags: haproxy
