- name: Gather facts from all hosts
  hosts: all
  gather_facts: yes
  tasks: []

- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS servers
  hosts: dns_servers
  roles:
    - bind
  tags: bind

- name: DNS resolver servers
  hosts: all
  gather_facts: yes
  roles: 
    - resolve
  tags: bind

- name: Database servers
  hosts: db_servers
  roles:
    - mysql
  tags: mysql

- name: MySQL replication server
  hosts: db_servers
  roles:
    - mysql_replication
  tags: mysql

- name: Web servers
  hosts: web_servers
  roles:
    - docker
    - agama
    - nginx
  tags: nginx

- name: Logging server
  hosts: loki_servers
  roles:
    - loki
  tags: loki

- name: Prometheus server
  hosts: prometheus_servers
  roles:
    - nginx
    - prometheus
  tags: prom

- name: Grafana server
  hosts: grafana_servers
  roles:
    - docker
    - nginx
    - grafana
  tags: g

- name: HAProxy load balancers
  hosts: haproxy_servers
  roles:
    - haproxy
    - keepalived
  tags: haproxy
