---
- name: Initial setup
  hosts: all
  become: true
  roles:
    - init

- name: Web server
  hosts: web_servers
  become: true
  roles:
    - agama
    - uwsgi
    - nginx

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: DNS server
  hosts: dns_servers
  become: true
  gather_facts: yes
  roles:
    - bind

- name: DNS resolver
  hosts: all
  become: true
  gather_facts: yes
  roles: 
    - resolve

- name: Prometheus server
  hosts: prometheus
  roles:
    - nginx
    - prometheus
