- name: Initial setup
  hosts: all
  become: true
  roles:
    - init
  tags: i

- name: DNS server
  hosts: dns_servers
  become: true
  gather_facts: yes
  roles:
    - bind
  tags: b

- name: DNS resolver
  hosts: all
  become: true
  gather_facts: yes
  roles: 
    - resolve
  tags: r

- name: Docker servers
  hosts: docker
  roles:
    - docker
  tags: d

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: m

- name: Influx DB
  hosts: influxdb
  roles:
    - influxdb
  tags: if

- name: Prometheus server
  hosts: prometheus
  roles:
    - nginx
    - prometheus
  tags: p

- name: Grafana
  hosts: grafana
  roles:
    - nginx
    - grafana
  tags: g

- name: Agama client
  hosts: agama_client
  roles:
    - agama_client
  tags: ac

- name: Web server
  hosts: web_servers
  become: true
  roles:
    - agama
      #    - uwsgi
    - nginx
  tags: w

- name: Keepalived service
  hosts: keepalived
  roles:
    - keepalived
  tags: k
