- name: Initial setup
  hosts: all
  become: true
  roles:
    - init
  tags: i

- name: Database servers
  hosts: db_servers
  become: true
  roles:
    - mysql

- name: Web Servers
  hosts: web_servers
  become: true
  roles:
    - agama
    - nginx
    - uwsgi
