{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Loki Backup Age (seconds)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"orinocoz\", service=\"loki\"}"
    }
   ]
  },
  {
   "title": "Prometheus Backup Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "backups_total{user=\"orinocoz\", service=\"prometheus\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Loki Backup Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "backups_total{user=\"orinocoz\", service=\"loki\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Last MySQL Backup Age (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"orinocoz\", service=\"mysql\"}"
    }
   ]
  },
  {
   "title": "Last Prometheus Backup Age (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"orinocoz\", service=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "MySQL Backup Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "backups_total{user=\"orinocoz\", service=\"mysql\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}