{
 "title": "HAProxy & Keepalived",
 "tags": [
  "haproxy",
  "keepalived"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "HAProxy UP - orinocoz-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_up{instance=~\"orinocoz-1.*\"}",
     "legendFormat": "orinocoz-1"
    }
   ]
  },
  {
   "title": "HAProxy UP - orinocoz-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_up{instance=~\"orinocoz-2.*\"}",
     "legendFormat": "orinocoz-2"
    }
   ]
  },
  {
   "title": "Keepalived UP - orinocoz-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "keepalived_up{instance=~\"orinocoz-1.*\"}",
     "legendFormat": "orinocoz-1"
    }
   ]
  },
  {
   "title": "Keepalived UP - orinocoz-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "keepalived_up{instance=~\"orinocoz-2.*\"}",
     "legendFormat": "orinocoz-2"
    }
   ]
  },
  {
   "title": "Keepalived VRRP State - orinocoz-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=~\"orinocoz-1.*\"}",
     "legendFormat": "orinocoz-1"
    }
   ]
  },
  {
   "title": "Keepalived VRRP State - orinocoz-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=~\"orinocoz-2.*\"}",
     "legendFormat": "orinocoz-2"
    }
   ]
  },
  {
   "title": "HAProxy Backend Servers Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{server}}" }
   ]
  }
 ]
}