{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Server IDs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read-Only Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication SQL Threads ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication IO Threads ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}