{
 "title": "Main Copy 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"items\") FROM \"agama-stats\"  WHERE $timeFilter GROUP BY time($__interval)"
    },
    {}
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "A Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}